name: ci

on: [push, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: "11"
            artifact-version: ""
          - java-version: "8"
            artifact-version: "-java-8"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Compile
        run: ./gradlew compileJava
        env:
          ARTIFACT_VERSION: ${{ matrix.artifact-version }}

  publish:
    needs: [compile]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: "11"
            artifact-version: ""
          - java-version: "8"
            artifact-version: "-java-8"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Publish to maven
        run: |
          ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_PUBLISH_REGISTRY_URL: "https://s01.oss.sonatype.org/content/repositories/releases/"
          ARTIFACT_VERSION: ${{ matrix.artifact-version}}
